services:
  sm-jelly:
    build: .
    image: sm-jelly:latest
    platform: linux/amd64
    env_file: .env
    volumes:
      - ./config.docker.yaml:/app/config.yaml:ro
      - ./workspace:/workspace
